# Generated by Django 5.1.6 on 2025-02-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_ID', models.IntegerField(max_length=5)),
                ('game_name', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=255)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
